name: Follow-N-Star-Action

on:
  schedule:
    - cron: '0 12 * * WED'  # runs @12pm every Wednesday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v5.0.0 # checks-out repository under $GITHUB_WORKSPACE so workflow can access it

      - name: Setup Python
        uses: actions/setup-python@v6.0.0 # installs python version
        with:
          python-version: '3.13'

      - name: Install Packages  # installs Pip & requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Main
        env:
            # assign environment variable secrets
            PERSONAL_USERNAME: ${{ secrets.PERSONAL_USERNAME }}
            PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: python main.py

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)

      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # used to push changes
          branch: main